chat:	main.o message.o user.o chat.o mygetch.o
	g++ -o chat main.o message.o user.o chat.o mygetch.o
obj:	main.cpp message.cpp user.cpp chat.cpp mygetch.cpp
	g++ -c main.cpp message.cpp user.cpp chat.cpp mygetch.cpp
clean:
	rm -f *.o

